apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkainfraconfigs.admin.enmasse.io
  labels:
    app: enmasse
spec:
  group: admin.enmasse.io
  version: v1beta1
  scope: Namespaced
  names:
    kind: KafkaInfraConfig
    listKind: KafkaInfraConfigList
    singular: kafkainfraconfig
    plural: kafkainfraconfigs
  versions:
    - name: v1beta1
      served: true
      storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - version
          - kafka
          properties:
            version:
              type: string
            networkPolicy:
              type: object
              properties:
                ingress:
                  type: array
                egress:
                  type: array
            kafka:
              type: object
